apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: meeseeks-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: mr-meeseeks
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50