spring:
  profiles: cloud

  rabbitmq:
    host: ${cloudamqp.credentials.http_api_uri:localhost}

server:
  port: 8084
---
spring:
  profiles: kubernetes
  rabbitmq:
    host: rabbitmq
server:
  port: 8080



