spring:
  profiles: cloud

server:
  port: 8084

spring:
  rabbitmq:
    host: ${cloudamqp.credentials.http_api_uri:localhost}
---
spring:
  profiles: kubernetes

server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq

