apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: rabbitmq
  name: pvc0001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: rick-n-morty
      component: rabbitmq