apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rick-n-morty
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.6.14-management-alpine
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq/mnesia/rabbit"
          name: rabbitmq-volume
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: pvc0001